# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - test

pool:
  vmImage: "ubuntu-latest"
  Image: cypress/browsers:node12.16.2-chrome81-ff75
variables:
  - group: testAutomation
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      echo $(userName) 
       npm install
       npm run cyp
    displayName: "npm install"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: cypress/videos
      ArtifactName: videos
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "cypress/screenshots"
      ArtifactName: "screenshots"
    condition: Failed()
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "*.xml"
      searchFolder: "$(System.DefaultWorkingDirectory)/tests/"
      mergeTestResults: true
      testRunTitle: "Publish test results"
    condition: succeededOrFailed()